### ISSUE TITLE
This EFI can boot to install bigsur, but after the installation, I enter the system phase and get stuck in SIP_ Off, my model is v5-573g. I hope it can help you

### ISSUE THREAD

**Issue by XPGeek6** [xtrs84zk/Aspire-V5-573P-Hackintosh#2]
[EFI.zip](https://github.com/xtrs84zk/Aspire-V5-573P-Hackintosh/files/5012371/EFI.zip)

**Comment by xtrs84zk** [comment]
Huh, weird. I'll take a look at your EFI. Did you try disabling SIP with [the new value](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html#disabling-sip)? 

> FF0F0000

**Comment by xtrs84zk** [comment]
Got Big Sur installed with your EFI and booted the container with a modified Clover. Weird I haven't been able to do it with OpenCore. I'll push the changes needed to the Clover branch by tomorrow. 

![Screen Shot 2020-08-04 at 20.38.43.png](https://user-images.githubusercontent.com/14208092/89369476-d3399100-d6a3-11ea-91ed-71c6d2b2cd85.png)

**Comment by XPGeek6** [comment]
I have tried FF0F0000, but still to no avail






肖鹏
技术总监
速客生鲜百货


 联系我









&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xtrs84zk/Aspire-V5-573P-Hackintosh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月5日(星期三) 凌晨1:48
收件人:&nbsp;"xtrs84zk/Aspire-V5-573P-Hackintosh"<Aspire-V5-573P-Hackintosh@noreply.github.com&gt;;
抄送:&nbsp;"『艺』犹未尽囗"<2284417401@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xtrs84zk/Aspire-V5-573P-Hackintosh] This EFI can boot to install bigsur, but after the installation, I enter the system phase and get stuck in SIP_ Off, my model is v5-573g. I hope it can help you (#2)





 
Huh, weird. I'll take a look at your EFI. Did you try disabling SIP with the new value?
  
FF0F0000

**Comment by XPGeek6** [comment]
The EFI I uploaded can be upgraded from 10.15.6 with 00000000. Bigsur (bate2) can be upgraded from 10.15.6. I will try to install bate4 again tonight.
&nbsp;




肖鹏
技术总监
速客生鲜百货


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Javier Sánchez"<notifications@github.com&gt;; 
发送时间: 2020年8月5日(星期三) 中午11:44
收件人: "xtrs84zk/Aspire-V5-573P-Hackintosh"<Aspire-V5-573P-Hackintosh@noreply.github.com&gt;; 
抄送: "『艺』犹未尽囗"<2284417401@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xtrs84zk/Aspire-V5-573P-Hackintosh] This EFI can boot to install bigsur, but after the installation, I enter the system phase and get stuck in SIP_ Off, my model is v5-573g. I hope it can help you (#2)





 
Got Big Sur installed with your EFI and booted the container with a modified Clover. Weird I haven't been able to do it with OpenCore. I'll push the changes needed to the Clover branch by tomorrow.

**Comment by xtrs84zk** [comment]
When looking the specs for the v5-573g, I found it has the same processor as my v5-573P.

When using your EFI to boot the installed system, it stalls on a kernel panic by an unsuccessful load of the kext for the iGPU 5000... I see you are using the SMBIOS of the MBP16,1 with the AAPL,ig-platform as 0600260A... if your 573g has the 4400 iGPU, you should use 0C00160A and 0A160000 for device-id. Try to match the SMBIOS with a machine that is on par with the processor you are running it in.

About the SIP thing, I managed to boot with the same mask used in Catalina to disable it, so... maybe there is an error before that one?

Other than that, there are a lot of patches that don't make sense in the v5-573g spec list I found. Tell me if the iGPU bit helped you.

**Comment by XPGeek6** [comment]
I remember that the version I sent you was modified from hd4600, so it has been changed to 0c00160a. The new EFI is attached






肖鹏
技术总监
速客生鲜百货


 联系我









&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xtrs84zk/Aspire-V5-573P-Hackintosh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 中午12:28
收件人:&nbsp;"xtrs84zk/Aspire-V5-573P-Hackintosh"<Aspire-V5-573P-Hackintosh@noreply.github.com&gt;;
抄送:&nbsp;"『艺』犹未尽囗"<2284417401@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xtrs84zk/Aspire-V5-573P-Hackintosh] This EFI can boot to install bigsur, but after the installation, I enter the system phase and get stuck in SIP_ Off, my model is v5-573g. I hope it can help you (#2)





 
When looking the specs for the v5-573g, it has the same processor as my -573P.
 
When using your EFI to boot the installed system, it stalls on a kernel panic by an unsuccessful load of the kext for the iGPU 5000... I see you are using the SMBIOS of the MBP16,1 with the AAPL,ig-platform as 0600260A... if your 573g has the 4400 iGPU, you should use 0C00160A and 0A160000 for device-id.
 
About the SIP thing, I managed to boot with the same mask used in Catalina to disable it, so... maybe there is an error before that one?
 
Other than that, there are a lot of patches that don't make sense in the -573g spec list I found. Tell me if the iGPU bit helped you.

**Comment by xtrs84zk** [comment]
Beta3 booted by switching VirtualSMC and its plugins for FakeSMC, I'm trying to boot beta4 by building VirtualSMC from source.

**Comment by xtrs84zk** [comment]
Beta2 booted by switching VirtualSMC and its plugins for FakeSMC, I'm trying to boot beta4 by building VirtualSMC from source.


Edit: Huh, i guess it was not fault of VirtualSMC/FakeSMC. It's Clover  injection. I'll keep trying with OpenCore then.

Edit2: This referenced the issue on Clover's repo and I can't find a way to unreference it from there. Sorry.

**Comment by xtrs84zk** [comment]
Fixed in [5e592fe](https://github.com/xtrs84zk/Aspire-V5-573P-Hackintosh/commit/5e592fe7821797a121f2d2aa9e3b3894f7a15b3c) on the OpenCore branch.
